# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone1_empresa', models.CharField(max_length=11)),
                ('telefone2_empresa', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='dadoscliente',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Responsavel'),
        ),
    ]
